#!/usr/bin/python3

#asks the user to input a sentence and stores it in the text variable
text=input("Enter your sentence: ")

#outputs the number of characters to the screen
print ("There are",len(text),"characters")
print ("And not including spaces is", len(text)-text.count(" "))


input("Press enter to close program")
